substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jdk/JDK21u3OrEarlier.java
substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jdk/JDK21u4OrLater.java
substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/thread/Target_java_lang_VirtualThread.java
substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/SecurityServicesFeature.java
substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/methodhandles/MethodHandleFeature.java
substratevm/src/com.oracle.svm.native.jvm.posix/src/JvmFuncs.c
substratevm/src/com.oracle.svm.native.libchelper/src/getThreadId.c
substratevm/src/com.oracle.svm.native.libchelper/src/getThreadUserTime.c

This PR replaces #1 and aims to make the GraalVM 23.1 version compatible with the upcoming OpenJDK 21.0.4 release. 
It is based on the corresponding [PR #738](https://github.com/graalvm/mandrel/pull/738) in the [graalvm/mandrel](https://github.com/graalvm/mandrel) repository ~~but fixes an issue in that PR by replacing the commit [Adopt "JDK-8324646: Avoid Class.forName in SecureRandom constructor"](https://github.com/graalvm/mandrel/pull/738/commits/46bd4103d3675f64e7c998aa81aa14cd634aeedc) which has a bug, with a version of the upstream commit [svm: adopt "JDK-8324646: Avoid Class.forName in SecureRandom constructor](https://github.com/oracle/graal/commit/05c1e79d360a9ab375eac31d1ce6946a311d74bc) adapted for OpenJDK 21.0.4~~ plus the fix from [PR …

GraalVM 23.1 backports for jdk21.0.4

---

substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jdk/JDK21u3OrEarlier.java
substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jdk/JDK21u4OrLater.java
substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jdk/RecomputedFields.java

Hi,
Please review this backport of a fix from graal master needed by [JDK-8328366](url) which got backported to JDK 21.0.5 (included in build 3 and better). It's the same as the upstream fix with the following modifications:
- Use `JDK21OrLater.class` rather than `JDK23OrLater.class`
- Fix up the import manually since the context around the added import changed.
**Testing**
I've run the quarkus integration test that failed before this backport and ran it again after it. Result is passed, issue is gone. See https://github.com/graalvm/mandrel/issues/780 for details.
Thoughts?

Backport: svm: adopt "JDK-8328366: Thread.setContextClassloader from thread in FJP commonPool task no longer works after JDK-8327501"

---

sdk/mx.sdk/mx_sdk_vm_impl.py
substratevm/src/com.oracle.svm.driver/src/com/oracle/svm/driver/NativeImage.java

This is a clean backport of https://github.com/oracle/graal/pull/7205 All three commits are simple `cherry-pick -x`.
With this, `mx --primary-suite vm --no-jlinking --env ce build` works. Similarly, `mx --primary-suite vm --env ce build`
still passes.
```
$ mx --primary-suite vm --no-jlinking --env ce graalvm-show
GraalVM distribution: GRAALVM_COMMUNITY_JAVA21
Version: 23.1.3
Config name: community
Components:
- Graal SDK Compiler ('sdkc', /graalvm, experimental)
- Graal SDK Native Image ('sdkni', /graalvm, experimental)
- GraalVM compiler ('cmp', /graal, experimental)
- LibGraal ('lg', /False, experimental)
- Native Image ('ni', /svm, experimental)
- Native Image Configure Tool ('nic', /svm, experimental)
- Native Image licence files ('nil', /svm, experimental)
- SubstrateVM ('svm', …
```

Fix build with --no-jlinking

---

substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/option/SubstrateOptionsParser.java

https://github.com/oracle/graal/pull/7406 was the original PR upstream. 9c5bcf994cd774a755be0fb548a3e3120a47605d is already present and this adds the second commit as well.
It's another backport we have in the Mandrel 23.1 downstream release repo and should move upstream.
Thoughts?

Partial backport of [GR-48529] Use the API flag in the init hint

---

sdk/src/org.graalvm.nativeimage/src/org/graalvm/nativeimage/impl/ReflectionRegistry.java
substratevm/mx.substratevm/mx_substratevm.py
substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/ConditionalConfigurationRegistry.java
substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/jni/JNIAccessFeature.java
substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/reflect/ReflectionDataBuilder.java
substratevm/src/com.oracle.svm.test/src/com/oracle/svm/test/ReflectionRegistrationTest.java

Almost a clean backport of: https://github.com/oracle/graal/pull/6985 to bring upstream community repo more in sync with downstream Mandrel 23.1 release branch.
The only difference is in https://github.com/graalvm/graalvm-community-jdk21u/commit/6af144fce4e6e541164082918070b29ce8111481 where the [original](https://github.com/oracle/graal/pull/6985/commits/d996f323b7c6ce796caccff6ae50bd1c2fa5a81f) had some import re-shuffeling and the rename from `methods` to `executables`, which isn't done in the backport.
Thoughts?

Backport: [GR-49816] Throw exception for null pointers passed to RuntimeJNIAccess / RuntimeReflection register methods

---

.github/workflows/main.yml
.github/workflows/quarkus.yml

Bump GHA versions so as to avoid deprecated warnings. See:
https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/

Various GHA bumps to avoid Nodejs deprecation warnings

---

compiler/mx.compiler/suite.py
espresso/mx.espresso/suite.py
regex/mx.regex/suite.py
sdk/mx.sdk/suite.py
substratevm/mx.substratevm/suite.py
tools/mx.tools/suite.py
truffle/external_repos/simplelanguage/pom.xml
truffle/external_repos/simplelanguage/sl
truffle/external_repos/simpletool/pom.xml
truffle/mx.truffle/suite.py
vm/mx.vm/suite.py
wasm/mx.wasm/suite.py

As PR title goes. Simple version bump. The release in October will be `23.1.5` (or `for JDK 21.0.5`).

New dev cycle GraalVM Community 23.1.5

---

substratevm/src/com.oracle.svm.core.genscavenge/src/com/oracle/svm/core/genscavenge/JfrGCHeapSummaryEvent.java
substratevm/src/com.oracle.svm.test/src/com/oracle/svm/test/jfr/AbstractJfrTest.java
substratevm/src/com.oracle.svm.test/src/com/oracle/svm/test/jfr/TestGCHeapSummaryEvent.java

Very minor backport of https://github.com/oracle/graal/pull/8653 to correct some values in the JFR GCHeapSummary event. 
Low risk because it only modifies hard coded values and adds test code. 
Tested with `mx native-unittest`: passed.

Backport of GR-52940: Fix reported values in GCHeapSummary JFR event

---

substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/SubstrateExitHandlerFeature.java

I'm backporting this change so that JFR is able to dump recordings by default if apps are stopped with SIGINT. This is important because without it users must manually specify a recording duration to create dump (or wait until the program finishes on its own). Previously `--install-exit-handlers` had to be specified at build time to get the same behaviour. 
This should be a low risk because the change only lessens the strictness of the check whether to install exist signal handlers.  This only changes the default behaviour when using JFR. 
Tested with `mx native-unittest`: passed
Also tested manually with:
```
mx native-image  --enable-monitoring=jfr -m jdk.httpserver
./jdk.httpserver -XX:StartFlightRecording=filename=rec.jfr 
SIGINT
jfr summary  rec.jfr
```

Backport of GR-52454: Include signal exit handlers in the image build if JFR

---

substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jdk/Resources.java

Backport of https://github.com/oracle/graal/commit/2368a2f047ee917660055d3d994a6195334bb725, part of https://github.com/oracle/graal/pull/7827 
The patch didn't apply cleanly but the adjustments where trivial in line 283 (dropped the extra boolean argument and kept `add` instead of `put` method)
(cherry picked from commit 2368a2f047ee917660055d3d994a6195334bb725)
Closes https://github.com/oracle/graal/issues/9038

Backport: Correctly handle resource include patterns

---

.github/workflows/main.yml
.github/workflows/quarkus.yml

[LabsJDK CE](https://github.com/graalvm/labs-openjdk-21/) is no longer maintained. Community builds should rely on OpenJDK builds instead.

Switch gates to use OpenJDK EA builds instead of LabsJDK

---

substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/substitute/AnnotationSubstitutionProcessor.java

Partial backport of https://github.com/oracle/graal/pull/8815
cherry picked from commit [30ae9d3c8dce269e1bcb9f1a090fddfff7d8eea4](https://github.com/oracle/graal/commit/30ae9d3c8dce269e1bcb9f1a090fddfff7d8eea4) trimmed to not include the API flag documentation change https://github.com/oracle/graal/commit/30ae9d3c8dce269e1bcb9f1a090fddfff7d8eea4#diff-b23354f77f5218c2b45167bd6d7887269ae1e8a91255e3db814e24706637327cL146-R146
Fixes https://github.com/oracle/graal/issues/1725
Reproducer:
```
cd /tmp
git clone --branch 2024-09-13-delete-no-class-def-found https://github.com/zakkak/issue-reproducers reproducers
cd reproducers
mvn package
java -cp target/classes Main
java \
-jar target/reproducer-1.0-SNAPSHOT.jar
native-image \
--no-fallback \
-H:+ReportExceptionStackTraces \
-jar …
```

Backport: Use JVMCI for @Delete classes

---

sdk/mx.sdk/mx_sdk_shaded.py
substratevm/mx.substratevm/mx_substratevm.py
sulong/mx.sulong/mx_sulong.py
sulong/mx.sulong/mx_sulong_suite_constituents.py

Backport of https://github.com/oracle/graal/pull/9877
The `pipes` python module has been removed in Python 3.13.
Fedora 41, for example has Python 3.13. This allows one to build the GraalVM for JDK 21 repo to build on that platform. The only difference to the graal/master commit is context change in `substratevm/mx.substratevm/mx_substratevm.py` and copyright year updates since the gates check for it.
Closes: https://github.com/oracle/graal/issues/10126

Backport: Avoid using deprecated pipes module

---

substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/phases/SharedGraphBuilderPhase.java

Clean backport of https://github.com/oracle/graal/pull/10320
Closes https://github.com/graalvm/graalvm-community-jdk21u/issues/32

[Backport] Improve causalilty reporting for unresolved elements

---

substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/thread/Target_java_lang_Thread.java

'getStackTrace0' is only used in asyncGetStackTrace() which is deleted as well.
Thread.getStackTrace()  is replaced by PlatformThreads.getStackTrace(). So it's not
reachable.
'getNextThreadIdOffset()' is only used in ThreadIdentifiers private class which is
substituted in JDKs better than JDK 19 (which includes 21). So won't be reachable either.
Fixes: https://github.com/graalvm/graalvm-community-jdk21u/issues/28
This is a partial backport of:
"Introudce a mode to unconditionally include classes" https://github.com/oracle/graal/commit/369f0ff8
to address https://github.com/oracle/graal/issues/9672
Only take the java.lang.Thread native method deletions as that's sufficient to fix
the issue reported in https://github.com/graalvm/graalvm-community-jdk21u/issues/28.

[Backport]  Delete native methods from java.lang.Thread

---

compiler/mx.compiler/suite.py
espresso/mx.espresso/suite.py
regex/mx.regex/suite.py
sdk/mx.sdk/suite.py
substratevm/mx.substratevm/suite.py
tools/mx.tools/suite.py
truffle/mx.truffle/suite.py
vm/mx.vm/suite.py

Done using:
```
find -name "suite.py" -exec sed -i 's|"release" : False|"release" : True|g' {} \;
```

Mark suite files for 23.1.6 release

---

compiler/src/jdk.internal.vm.compiler/src/org/graalvm/compiler/hotspot/replacements/MonitorSnippets.java

The lowering of MonitorEnterNode and MonitorExitNode has an issue where it "pushes" more arguments than needed by the callee (monitorenterStub and monitorexitStub, respectively) when JVMCIUseFastLocking is disabled. See Stacktrace on the JBS issue. The issue isn't present in Graal mainline because there was some refactoring in the code which fixed the issue.
Tested internally in Linux & Mac using JTREG & JCK.
JBS issue: https://bugs.openjdk.org/browse/JDK-8349158
Fixes: https://github.com/graalvm/graalvm-community-jdk21u/issues/43

8349158: ArrayIndexOutOfBoundsException in MonitorSnippets.java

---

common.json
compiler/src/jdk.internal.vm.compiler.test/src/org/graalvm/compiler/jtt/lang/Double_isInfinite.java
compiler/src/jdk.internal.vm.compiler.test/src/org/graalvm/compiler/nodes/test/OpaqueNodeTest.java
compiler/src/jdk.internal.vm.compiler/src/org/graalvm/compiler/core/phases/EconomyLowTier.java
compiler/src/jdk.internal.vm.compiler/src/org/graalvm/compiler/core/phases/LowTier.java
compiler/src/jdk.internal.vm.compiler/src/org/graalvm/compiler/nodes/extended/OpaqueValueNode.java
compiler/src/jdk.internal.vm.compiler/src/org/graalvm/compiler/phases/common/RemoveOpaqueValuePhase.java
espresso/src/com.oracle.truffle.espresso.jdwp/src/com/oracle/truffle/espresso/jdwp/impl/DebuggerController.java
sdk/src/org.graalvm.nativeimage/src/org/graalvm/nativeimage/c/type/CCharPointer.java
sdk/src/org.graalvm.polyglot/src/org/graalvm/polyglot/Engine.java
substratevm/src/com.oracle.svm.core.posix/src/com/oracle/svm/core/posix/PosixSystemPropertiesSupport.java
substratevm/src/com.oracle.svm.core.posix/src/com/oracle/svm/core/posix/PosixUtils.java
substratevm/src/com.oracle.svm.core.posix/src/com/oracle/svm/core/posix/headers/Pwd.java
substratevm/src/com.oracle.svm.core.posix/src/com/oracle/svm/core/posix/jvmstat/PosixPerfMemoryProvider.java
substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jdk/RuntimeModuleSupport.java
substratevm/src/com.oracle.svm.graal/src/com/oracle/svm/graal/hosted/ParseOnceRuntimeCompilationFeature.java
substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/ModuleLayerFeature.java
substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/c/query/QueryResultParser.java
substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/code/SubstrateCompilationDirectives.java
substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/phases/DeoptimizationTargetBciBlockMapping.java
truffle/src/com.oracle.truffle.api.test/src/com/oracle/truffle/api/test/polyglot/LoggingTest.java

2nd batch of https://github.com/graalvm/graalvm-community-jdk21u/issues/37
Backports:
* https://github.com/oracle/graal/pull/8107
* https://github.com/oracle/graal/pull/8491
* https://github.com/oracle/graal/pull/8950
* https://github.com/oracle/graal/pull/8865
* https://github.com/oracle/graal/pull/8436
* https://github.com/oracle/graal/pull/8721
* https://github.com/oracle/graal/pull/8830
> [!NOTE]
> * `790e3c0616b [GR-52958] Backport to 23.1: Fix values reported in JFR event GCHeapSummary.` is not part of this backport because it has been separately backported in https://github.com/graalvm/graalvm-community-jdk21u/pull/2
> * `df72edaee97 [GR-53729] Backport to 23.1: Fix AArch64AtomicMove.` is not part of this backport because it has been separately backported in …

Merge upstream vm-23.1.5 tag 2nd batch

---

common.json
compiler/src/jdk.internal.vm.compiler.test/src/org/graalvm/compiler/core/test/SubprocessTest.java
compiler/src/jdk.internal.vm.compiler.test/src/org/graalvm/compiler/core/test/VerifyFoldableMethods.java
compiler/src/jdk.internal.vm.compiler/src/org/graalvm/compiler/hotspot/GraalHotSpotVMConfig.java
compiler/src/jdk.internal.vm.compiler/src/org/graalvm/compiler/hotspot/replacements/HotSpotG1WriteBarrierSnippets.java
compiler/src/jdk.internal.vm.compiler/src/org/graalvm/compiler/hotspot/replacements/HotSpotReplacementsUtil.java
compiler/src/jdk.internal.vm.compiler/src/org/graalvm/compiler/hotspot/stubs/ForeignCallSnippets.java
compiler/src/jdk.internal.vm.compiler/src/org/graalvm/compiler/replacements/ReplacementsUtil.java
compiler/src/jdk.internal.vm.compiler/src/org/graalvm/compiler/replacements/gc/G1WriteBarrierSnippets.java
compiler/src/jdk.internal.vm.compiler/src/org/graalvm/compiler/truffle/compiler/KnownTruffleTypes.java
compiler/src/jdk.internal.vm.compiler/src/org/graalvm/compiler/truffle/compiler/PEAgnosticInlineInvokePlugin.java
compiler/src/jdk.internal.vm.compiler/src/org/graalvm/compiler/truffle/compiler/phases/inlining/AgnosticInliningPhase.java
compiler/src/jdk.internal.vm.compiler/src/org/graalvm/compiler/truffle/compiler/phases/inlining/CallNode.java
compiler/src/jdk.internal.vm.compiler/src/org/graalvm/compiler/truffle/compiler/phases/inlining/GraphManager.java
substratevm/src/com.oracle.graal.pointsto/src/com/oracle/graal/pointsto/ObjectScanner.java
substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jdk/SecuritySubstitutions.java
substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/monitor/JavaMonitor.java
substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/monitor/JavaMonitorQueuedSynchronizer.java
substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/methodhandles/MethodHandleFeature.java
substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/reflect/ReflectionDataBuilder.java
truffle/src/com.oracle.truffle.runtime/src/com/oracle/truffle/runtime/debug/TraceCompilationListener.java

8th batch of https://github.com/graalvm/graalvm-community-jdk21u/issues/37
Backports:
* https://github.com/oracle/graal/pull/9579
* https://github.com/oracle/graal/pull/9553
* https://github.com/oracle/graal/commit/27c16d50bffedab6b24ab4784eec9407342e3dcd from https://github.com/oracle/graal/pull/9012
* https://github.com/oracle/graal/pull/9583
* https://github.com/oracle/graal/pull/9572
Conflict 
``` diff
diff --cc substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/reflect/ReflectionDataBuilder.java
index a5e62695a6b,ddacb66b38a..00000000000
--- a/substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/reflect/ReflectionDataBuilder.java
+++ b/substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/reflect/ReflectionDataBuilder.java
@@@ -1010,12 -993,16 …
```

Merge upstream vm-23.1.5 tag 8th batch

---

substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/io/Utf8.java
substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/util/Utf8.java

Backport of `JDK-8314794: Improve UTF8 String supports`
Cherry picked from commit https://github.com/oracle/graal/pull/9774/commits/55609a7014b92a635d29e78b2a252a7417440301
Only removed the `@BasedOnJDKFile` annotation and converted it to a comment as it is not supported here
This is part of https://github.com/graalvm/graalvm-community-jdk21u/issues/64

[Backport] svm: Adopt "JDK-8314794: Improve UTF8 String supports" [GR-58535]

---

substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/SubstrateOptions.java
substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/substitute/AnnotationSubstitutionProcessor.java

Backport Add option to disable substitutions
Cherry picked from commit https://github.com/oracle/graal/pull/9743/commits/65e51884595a88cfb9a8ba6d0d9dc81bed6b3c44
Resolved conflict by keeping local changes and adding only what was added in the commit to the source and changed `AccumulatingLocatableMultiOptionValue` to `LocatableMultiOptionValue` as in upstream `LocatableMultiOptionValue` was renamed to `AccumulatingLocatableMultiOptionValue`
This is part of https://github.com/graalvm/graalvm-community-jdk21u/issues/64

[Backport] [GR-58292] Add option to disable substitutions

---

sulong/tests/com.oracle.truffle.llvm.tests.llirtestgen.native/prelude.c

Partial backport of https://github.com/oracle/graal/pull/7642 (includes only https://github.com/oracle/graal/commit/3590395d5a2fad848f5305fb606b6b9a040e4cf0)
~Draft until test runs ok.~
Closes: #67 
(cherry picked from commit 3590395d5a2fad848f5305fb606b6b9a040e4cf0)

[Backport] Flip a bit in test input to avoid unspecified NaN behavior in bitcode tests.

---

substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/methodhandles/MethodHandleFeature.java

[GR-58531] Backport Eagerly initialize caches in method handle implementation
Cherry picked from commit https://github.com/oracle/graal/commit/6e859d90dde01a23e6973e25984419f29edc9c2b
Resolved conflicts by keeping the changes only related to the original change and not changing stuff that wasn't related to the actual commit, also added `false` as a first parameter to `ReflectionUtil.lookupClass` as here we do not have an overload that passes optional=false as default.

[Backport] [GR-58531] Eagerly initialize caches in method handle implementation

---

compiler/src/jdk.internal.vm.compiler/src/org/graalvm/compiler/lir/amd64/AMD64SHA1Op.java
compiler/src/jdk.internal.vm.compiler/src/org/graalvm/compiler/lir/amd64/AMD64SHA256Op.java

This PR backports the [GR-60402](https://github.com/oracle/graal/issues/10275) as part of the [[Backport] Oracle GraalVM for JDK 21.0.7 backports and fixes](https://github.com/graalvm/graalvm-community-jdk21u/issues/66#top) effort.
Changes:
- cherry-picked the https://github.com/oracle/graal/commit/2a2e50be111569b6dfa4e5b646dc5f6d65085bbd fix
- resolved a minor merge conflict in the Java import section
Impact:
- improves the performance of cryptographic operations on hardware with Intel SHA extensions (SHA-NI)
Verification:
- tested with JTREG tests on an Intel Xeon Gold 6455B (supports SHA-NI instructions)

[GR-60402] Add vzeroupper upon the entrance of AMD64 sha1 and sha256 stubs.

---

substratevm/src/com.oracle.svm.core.posix/src/com/oracle/svm/core/posix/PosixUtils.java
substratevm/src/com.oracle.svm.core.posix/src/com/oracle/svm/core/posix/headers/Pwd.java

This PR backports the [GR-59499](https://github.com/oracle/graal/issues/9939) as part of the https://github.com/graalvm/graalvm-community-jdk21u/issues/66#top effort.
Changes:
- cherry-picked the https://github.com/oracle/graal/commit/015a8f7fdd5594b7bfbe5de266c7bb56e36dd9de fix
- resolved a merge conflict in PosixUtils.getUserNameOrDir(..) caused by the missing [native memory tracker](https://github.com/oracle/graal/commit/adab8a8a4bace12e7455aa79b77f21c1e85623da) in graalvm-jdk21u
<details>
<summary>merge conflict resolution details</summary>
Here is the diff: the original change (left) and a change applied to graalvm-jdk21u (right)
```diff
commit aade614612ab24d9642a5d3bbfd40a3c437f0e5b                                                    |    commit …
```

[Backport][GR-59499] Fix System.getProperties() when called from virtual thread.

---

substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/NativeImageClassLoaderSupport.java

Since we already execute all calls to
NativeImageClassLoaderSupport.LoadClassHandler#handleClassFileName via the ForkJoinPool.commonPool(), the use of parallelStream() here does not further increase parallel execution and can be replaced with a simple forEach without increasing class initialization time.
Additionally, avoiding parallelStream() fixes a deadlock that was observable when only one CPU core is available (parallel streams also use the commonPool() and this can lead to a deadlock with our own use on single core systems).
(cherry picked from commit 8ecf1132b617721d9bf224191430fb31786b5f5f)
Closes: https://github.com/graalvm/graalvm-community-jdk21u/issues/76

[Backport][GR-63455] Remove pointless parallel stream processing for classpath entries.

---

substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/monitor/JavaMonitorQueuedSynchronizer.java

This PR backports the [GR-62340](https://github.com/oracle/graal/pull/10722) as part of the https://github.com/graalvm/graalvm-community-jdk21u/issues/66 effort.
Changes:
- cherry-picked the https://github.com/oracle/graal/commit/07421a71ab0a1a628cfbe42cfff0cf690f640317 fix
- (clean backport)
Impact
- Fixes under- or over-re-acquisition of the monitor in SubstrateVM’s fallback path after an OutOfMemoryError

[Backport][GR-62340] Use correct acquisition count in acquireOnOOME.

---

tools/src/com.oracle.truffle.tools.profiler/src/com/oracle/truffle/tools/profiler/impl/CPUSamplerCLI.java

- https://github.com/oracle/graal/pull/10524
- a simple change to correct CPU sampler’s tier_count value
**Testing:** tools/mx.tools unit tests: no regressions.
**This PR is a part of the** [Oracle GraalVM for JDK 21.0.7 backports and fixes](https://github.com/graalvm/graalvm-community-jdk21u/issues/66)

[Backport][GR-61481] Fix tier_count values in CPU sampler JSON output.

---

wasm/src/org.graalvm.wasm/src/org/graalvm/wasm/nodes/WasmFunctionNode.java

(cherry picked from commit 7a6e19a38d8ab0f12a605aab6411438b6fd47e7c)
- https://github.com/oracle/graal/pull/10958
**Conflicts:**
Import conflict in `wasm/src/org.graalvm.wasm/src/org/graalvm/wasm/nodes/WasmFunctionNode.java`
**Closes:** https://github.com/graalvm/graalvm-community-jdk21u/issues/77

GR-63770: Add missing Truffle Safepoint poll in Wasm interpreter loop.

---

compiler/src/jdk.internal.vm.compiler/src/org/graalvm/compiler/lir/amd64/AMD64ArrayIndexOfOp.java

- https://github.com/oracle/graal/pull/10869
- https://github.com/oracle/graal/commit/253bb4a6cd66b3bf4cf8a67a4f9a29ac1046f29b
**Closes:** https://github.com/graalvm/graalvm-community-jdk21u/issues/112

[Backport] [Oracle GraalVM] [GR-63092] Backport to 23.1: Use dword comparisons in AMD64ArrayIndexOfOp because search values are definitely int

---

compiler/src/jdk.internal.vm.compiler/src/org/graalvm/compiler/hotspot/aarch64/AArch64HotSpotMove.java
compiler/src/jdk.internal.vm.compiler/src/org/graalvm/compiler/hotspot/amd64/AMD64HotSpotMove.java
compiler/src/jdk.internal.vm.compiler/src/org/graalvm/compiler/lir/StandardOp.java
compiler/src/jdk.internal.vm.compiler/src/org/graalvm/compiler/lir/aarch64/AArch64Move.java
compiler/src/jdk.internal.vm.compiler/src/org/graalvm/compiler/lir/alloc/lsra/LinearScanLifetimeAnalysisPhase.java
compiler/src/jdk.internal.vm.compiler/src/org/graalvm/compiler/lir/amd64/AMD64Move.java
compiler/src/jdk.internal.vm.compiler/src/org/graalvm/compiler/lir/amd64/vector/AMD64VectorMove.java
substratevm/src/com.oracle.svm.core.graal.aarch64/src/com/oracle/svm/core/graal/aarch64/AArch64LoadMethodPointerConstantOp.java
substratevm/src/com.oracle.svm.core.graal.aarch64/src/com/oracle/svm/core/graal/aarch64/SubstrateAArch64Backend.java
substratevm/src/com.oracle.svm.core.graal.amd64/src/com/oracle/svm/core/graal/amd64/AMD64LoadMethodPointerConstantOp.java
substratevm/src/com.oracle.svm.core.graal.amd64/src/com/oracle/svm/core/graal/amd64/SubstrateAMD64Backend.java

- https://github.com/oracle/graal/pull/10910
- https://github.com/oracle/graal/commit/b708a4e509f5f6c84e223c663e6596ea2a173089
<details>
```
<<<<<<< HEAD
import static jdk.vm.ci.code.ValueUtil.asRegister;
import static org.graalvm.compiler.lir.LIRInstruction.OperandFlag.HINT;
import static org.graalvm.compiler.lir.LIRInstruction.OperandFlag.REG;
import org.graalvm.compiler.asm.aarch64.AArch64MacroAssembler;
import org.graalvm.compiler.lir.LIRInstructionClass;
import org.graalvm.compiler.lir.StandardOp;
import org.graalvm.compiler.lir.aarch64.AArch64LIRInstruction;
import org.graalvm.compiler.lir.asm.CompilationResultBuilder;
import com.oracle.svm.core.meta.SubstrateMethodPointerConstant;
=======
import static …
```

[Backport] [Oracle GraalVM] [GR-63522] Backport to 23.1: Prevent rematerialization of SVM's LoadCompressedObjectConstantOp

---

truffle/src/com.oracle.truffle.api.dsl.test/src/com/oracle/truffle/api/dsl/test/GR62540Test.java
truffle/src/com.oracle.truffle.dsl.processor/src/com/oracle/truffle/dsl/processor/generator/FlatNodeGenFactory.java

- https://github.com/oracle/graal/pull/10779
- https://github.com/oracle/graal/commit/4ff4aa89a7da5ed2e97739cec9b200f8a8af1516
**Conflicts:**
```java
<<<<<<< HEAD
TypeMirror returnType = forType.getReturnType();
if (!isVoid(returnType) && !isSubtypeBoxed(context, specialization.getReturnType().getType(), returnType) &&
!isSubtypeBoxed(context, returnType, specialization.getReturnType().getType())) {
continue outer;
=======
TypeMirror executeReturnType = forType.getReturnType();
TypeMirror specializationReturnType = specialization.lookupBoxingOverloadReturnType(forType);
if (isReturnTypeCompatible(executeReturnType, specializationReturnType)) {
filteredSpecializations.add(specialization);
>>>>>>> 4ff4aa89a7d (Fix return type compatibility check can lead to void …
```

[Backport] [Oracle GraalVM] [GR-62969] Backport to 23.1: Fix return type compatibility check can lead to void specializations being filtered.

---

wasm/src/org.graalvm.wasm/src/org/graalvm/wasm/nodes/WasmFunctionNode.java

- https://github.com/oracle/graal/commit/7a6e19a38d8ab0f12a605aab6411438b6fd47e7c
**Conflicts:**
Minor conflict:
```
<<<<<<< HEAD
import com.oracle.truffle.api.TruffleContext;
=======
import com.oracle.truffle.api.TruffleSafepoint;
>>>>>>> 7a6e19a38d8 (Add missing Truffle Safepoint poll in Wasm interpreter loop.)
```
resolution: accept both imports as they both are used in a class
Closes: https://github.com/graalvm/graalvm-community-jdk21u/issues/103

[Backport] [Oracle GraalVM] [GR-63770] Backport to 23.1: Missing Truffle Safepoint poll in bytecode interpreter loop.

---

substratevm/src/com.oracle.svm.core.genscavenge/src/com/oracle/svm/core/genscavenge/ChunkedImageHeapAllocator.java
substratevm/src/com.oracle.svm.core.genscavenge/src/com/oracle/svm/core/genscavenge/ChunkedImageHeapPartition.java
substratevm/src/com.oracle.svm.core.genscavenge/src/com/oracle/svm/core/genscavenge/LinearImageHeapPartition.java
substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/image/ImageHeapPartition.java
substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/image/NativeImageDebugInfoProvider.java

- https://github.com/oracle/graal/pull/10894
- https://github.com/oracle/graal/commit/a9bbe92ec669adb1620152922209108637fd0bf5
```java
<<<<<<< HEAD
import org.graalvm.compiler.core.common.NumUtil;
=======
>>>>>>> a9bbe92ec66 (Don't assume that partitions with offset 0 are fillers.)
<<<<<<< HEAD
private static class SizeComparator implements Comparator<ImageHeapObject> {
=======
@Override
public boolean isFiller() {
return false;
}
@Override
public String toString() {
return name;
}
private static final class SizeComparator implements Comparator<ImageHeapObject> {
>>>>>>> a9bbe92ec66 (Don't assume that partitions with offset 0 are fillers.)
```
collision due to missing toString method and SizeComparator is not final on graal-jdk21 version 
resolution: …

[Backport] [Oracle GraalVM] [GR-63403] Backport to 23.1: Don't assume that partitions with offset 0 are fillers.

---

compiler/src/jdk.internal.vm.compiler/src/org/graalvm/compiler/lir/amd64/AMD64ArrayIndexOfOp.java

- https://github.com/oracle/graal/pull/10916
- https://github.com/oracle/graal/commit/15877a2cfffc1c8c56a13842cf9d6b73a8257e21
**Conflicts:**
<details>
```java
<<<<<<< HEAD:compiler/src/jdk.internal.vm.compiler/src/org/graalvm/compiler/lir/amd64/AMD64ArrayIndexOfOp.java
import static org.graalvm.compiler.asm.amd64.AMD64MacroAssembler.ExtendMode.ZERO_EXTEND;
import static org.graalvm.compiler.lir.LIRInstruction.OperandFlag.ILLEGAL;
import static org.graalvm.compiler.lir.LIRInstruction.OperandFlag.REG;
import static org.graalvm.compiler.lir.LIRInstruction.OperandFlag.STACK;
import java.util.EnumSet;
import org.graalvm.compiler.asm.Label;
import org.graalvm.compiler.asm.amd64.AMD64Address;
import org.graalvm.compiler.asm.amd64.AMD64Assembler;
import …
```

[Backport] [Oracle GraalVM] [GR-63484] Backport to 23.1: AMD64ArrayIndexOfOp: Fix short jump across unknown alignment.

---

substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/graal/jdk/SubstrateObjectCloneSnippets.java

- Part of https://github.com/oracle/graal/pull/10835 
- https://github.com/oracle/graal/commit/7eab68b6200d6f4995c30dc26d6c3570760baccf
(A simple but crucial change — concurrent reads of uninitialized memory have never been safe)
Complements https://github.com/graalvm/graalvm-community-jdk21u/pull/131
**Conflicts:** Import packet names collision and minor doClone method disparity due to subsequent change on mainline: https://github.com/oracle/graal/commit/c24f5970307751aa1a93f241bdc14052a3d42109
<details>
```
<<<<<<< HEAD
import org.graalvm.compiler.api.replacements.Snippet;
import org.graalvm.compiler.core.common.NumUtil;
import org.graalvm.compiler.core.common.spi.ForeignCallDescriptor;
import org.graalvm.compiler.graph.Node;
import …
```

[Backport] [Oracle GraalVM] [GR-62941] Backport to 23.1: Memory barrier after Object.clone() is missing.

---

compiler/mx.compiler/suite.py
espresso/mx.espresso/suite.py
regex/mx.regex/suite.py
sdk/mx.sdk/suite.py
substratevm/mx.substratevm/suite.py
tools/mx.tools/suite.py
truffle/mx.truffle/suite.py
vm/mx.vm/suite.py
wasm/mx.wasm/suite.py

Usual version bump since 23.1.9 development is now starting.
CI will fail due to #157 which I intend to fix next. This patch builds fine with the latest 21.0.8 GA JDK.

Mark suite files for upcoming 23.1.9 release

---

truffle/src/com.oracle.truffle.polyglot/src/com/oracle/truffle/polyglot/ObjectSizeCalculator.java

- https://github.com/oracle/graal/pull/10374
**Closes:** none
It is a part of [[Backport] Oracle GraalVM for JDK 21.0.6 backports and fixes](https://github.com/graalvm/graalvm-community-jdk21u/issues/64)

[Backport][GR-60694] Fix int overflow in ObjectSizeCalculator#increaseByArraySize.

---

compiler/src/jdk.internal.vm.compiler.test/src/org/graalvm/compiler/replacements/test/UnsafeReplacementsTest.java
compiler/src/jdk.internal.vm.compiler/src/org/graalvm/compiler/core/amd64/AMD64LIRGenerator.java

- https://github.com/oracle/graal/pull/10898 (https://github.com/oracle/graal/commit/f8a4ca05236753d6c5bdca0b616c01244e5acca1)
**Conflicts [1]**
Since https://github.com/oracle/graal/commit/23cbacb7e4d11224743ae5279aaf5f06699bf11a on mainline emitCompareAndSwapBranch & emitCompareAndSwapOp have isLogic parameter:
```diff
-    public void emitCompareAndSwapBranch(LIRKind kind, AMD64AddressValue address, Value expectedValue, Value newValue, Condition condition, LabelRef trueLabel, LabelRef falseLabel,
+    public void emitCompareAndSwapBranch(boolean isLogic, LIRKind kind, AMD64AddressValue address, Value expectedValue, Value newValue, Condition condition, LabelRef trueLabel, LabelRef falseLabel,
-    public void emitCompareAndSwapOp(LIRGeneratorTool tool, LIRKind …
```

[Backport] [Oracle GraalVM] [GR-63479] Backport to 23.1: Emit additional reinterpret when generating float CAS from node matching rules.

---

substratevm/src/com.oracle.svm.truffle/src/com/oracle/svm/truffle/TruffleBaseFeature.java
truffle/src/com.oracle.truffle.polyglot/src/com/oracle/truffle/polyglot/InstrumentCache.java
truffle/src/com.oracle.truffle.polyglot/src/com/oracle/truffle/polyglot/InternalResourceRoots.java
truffle/src/com.oracle.truffle.polyglot/src/com/oracle/truffle/polyglot/LanguageCache.java
truffle/src/com.oracle.truffle.polyglot/src/com/oracle/truffle/polyglot/PolyglotEngineImpl.java
truffle/src/com.oracle.truffle.polyglot/src/com/oracle/truffle/polyglot/PolyglotLoggers.java

- https://github.com/oracle/graal/pull/10231
- skipped: change in JDKSupport.java as the file was deleted in graalvm-community-jdk21u. 
- skipped: change in PolyglotEngineImpl.logCloseOnCollectedError (introduced in mainline only, https://github.com/oracle/graal/commit/c6b9e49f953347bf61b4d1ea2ecc3a9ae29c39ca)
Closes: https://github.com/graalvm/graalvm-community-jdk21u/issues/105

[Backport] [Oracle GraalVM] [GR-62678] Backport to 23.1 : System.out/err usage in PolyglotLoggers.

---

substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/thread/VMThreads.java

- https://github.com/oracle/graal/pull/10621
Closes: This is a part of [[Backport] Oracle GraalVM for JDK 21.0.7 backports and fixes](https://github.com/graalvm/graalvm-community-jdk21u/issues/66) effort

[Backport] [GR-61888] Fix @Uninterruptible

---

compiler/src/jdk.internal.vm.compiler/src/org/graalvm/compiler/nodes/ConditionAnchorNode.java
compiler/src/jdk.internal.vm.compiler/src/org/graalvm/compiler/nodes/FixedGuardNode.java
compiler/src/jdk.internal.vm.compiler/src/org/graalvm/compiler/nodes/PiNode.java
compiler/src/jdk.internal.vm.compiler/src/org/graalvm/compiler/truffle/compiler/substitutions/TruffleGraphBuilderPlugins.java

- https://github.com/oracle/graal/pull/7385
Minor conflict around [Simplify ValueAnchorNode implementation](https://github.com/oracle/graal/commit/d2ddd2b83f5dcbb59e6862fb9a6a452e4c451a1e) change: ValueAnchorNode(null)->ValueAnchorNode()
<details>
```
<<<<<<< HEAD
if (c.getValue() != negated) {
return null;
} else {
return new ValueAnchorNode();
=======
// An anchor that still has usages must still exist since it's possible the condition is
// true for control flow reasons so the Pi stamp is also only valid for those reason.
if (c.getValue() == negated || hasUsages()) {
return new ValueAnchorNode(null);
} else {
return null;
>>>>>>> 161b078bc21 (Do not permit FixedGuardNode and ConditionAnchorNode to go away if there are PiNodes attached)
``` …

[Backport][GR-45020] Do not permit FixedGuardNode and ConditionAnchorNode to go away if there are PiNodes attached

---

truffle/src/com.oracle.truffle.polyglot/src/com/oracle/truffle/polyglot/PolyglotContextImpl.java

- https://github.com/oracle/graal/pull/9623
**Closes:** none
It is a part of [[Backport] Oracle GraalVM for JDK 21.0.6 backports and fixes](https://github.com/graalvm/graalvm-community-jdk21u/issues/64)

[Backport][GR-57835] Remove dead threads from PolyglotContextImpl#threads during new thread initialization.

---

substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/SubstrateOptions.java
substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/image/CCLinkerInvocation.java
substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/image/NativeImageDebugInfoStripFeature.java

- https://github.com/oracle/graal/pull/9888
**Conflicts:** Minor conflict: a difference in a deleted code. <details>
```
<<<<<<< HEAD
private static Path createKeepSymbolsListFile(AfterImageWriteAccessImpl accessImpl) throws IOException {
Path exportedSymbolsPath = accessImpl.getTempDirectory().resolve("keep-symbols.list").toAbsolutePath();
Files.write(exportedSymbolsPath, accessImpl.getImageSymbols(true));
return exportedSymbolsPath;
}
=======
>>>>>>> 2784e64ca29 (Preserve local symbols if post-link stripping follows)
```
</details>
**Closes: none**
It is a part of [[Backport] Oracle GraalVM for JDK 21.0.6 backports and fixes](https://github.com/graalvm/graalvm-community-jdk21u/issues/64)

[Backport][GR-58571] Preserve local symbols if post-link stripping follows.

---

vm/mx.vm/suite.py

The update sets graal-js and graal-nodejs to graal-23.1.8 tag that includes GraalJS changes from [Oracle GraalVM for JDK 21.0.8 changelog](https://docs.oracle.com/en/graalvm/jdk/21/docs/release-notes/): 
- [GR-65310] Backport to 23.1: Dates with missing UTC offset should be interpreted (in nashorn-compat mode) as UTC time when they are "strict" only.
- [GR-64187] Backport to 23.1: Using latest double-conversion version 3.3.0.
- [GR-63246] Backport to 23.1: Fix ClassCastException in super property access.
- [GR-64709] Backport to 23.1: ExportValueNode.doTruffleObject() should exclude SafeIntegers.
- [GR-63059] Backport to 23.1: Map.prototype.forEach needs to import key and value of foreign hash entries.
- [GR-64697] Backport to 23.1: Correction of Array.prototype.flat() producing a foreign …

Update graal-js and graal-nodejs to GraalVM 23.1.8 (JDK 21.0.8)

---

substratevm/src/com.oracle.svm.core.genscavenge/src/com/oracle/svm/core/genscavenge/ObjectHeaderImpl.java
substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/identityhashcode/IdentityHashCodeSupport.java
substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/identityhashcode/SubstrateIdentityHashCodeFeature.java
substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/identityhashcode/SubstrateIdentityHashCodeSnippets.java

- https://github.com/oracle/graal/pull/10862 (https://github.com/oracle/graal/commit/ef8f0516a6ae245bc460f7987a060bab796a3390)
<details>
```
MERGE CONFLICT substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/identityhashcode/SubstrateIdentityHashCodeSnippets.java
<<<<<<< HEAD
if (ol.hasFixedIdentityHashField()) {
int offset = ol.getFixedIdentityHashOffset();
identityHashCode = ObjectAccess.readInt(obj, offset, IdentityHashCodeSupport.IDENTITY_HASHCODE_LOCATION);
if (probability(SLOW_PATH_PROBABILITY, identityHashCode == 0)) {
identityHashCode = generateIdentityHashCode(GENERATE_IDENTITY_HASH_CODE, obj);
}
return identityHashCode;
}
ObjectHeader oh = Heap.getHeap().getObjectHeader();
Word objPtr = Word.objectToUntrackedPointer(obj);
Word …
```

[Backport] [Oracle GraalVM] [GR-63266] Backport to 23.1: Prevent absent hashcode computation split across safepoint checks.

---

compiler/src/jdk.internal.vm.compiler/src/org/graalvm/compiler/nodes/PiNode.java

- https://github.com/oracle/graal/pull/8573
**Conflicts:**
A minor conflict regarding comment removal: `// GR-52557`
Applies cleanly only after https://github.com/graalvm/graalvm-community-jdk21u/pull/150
Closes: (none)
It is a part of: [[Backport] Oracle GraalVM for JDK 21.0.6 backports and fixes](https://github.com/graalvm/graalvm-community-jdk21u/issues/64)

[Backport][GR-52557] Pi node: guard against deletion in recursion.

---

substratevm/src/com.oracle.graal.pointsto/src/com/oracle/graal/pointsto/heap/ImageHeapScanner.java
substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/reflect/ReflectionDataBuilder.java

- https://github.com/oracle/graal/pull/10104
- https://github.com/oracle/graal/commit/d6da064e
**Conflicts:**
- Skipped change in markTypeInstantiated: not applicable — AnalysisType::registerAsInstantiated is not implemented.
- Skipped objectType.registerAsReachable call: the corresponding code does not exist in this codebase.
- Skipped change in NativeImageCodeCache.java: it modifies code introduced later, and relates only to a guarantee report, which is not important.
<details>
```
git cherry-pick f642457aa0d1fc67ab85eb7b4c62cf4946084164 -x
CONFLICT (content): Merge conflict in substratevm/src/com.oracle.graal.pointsto/src/com/oracle/graal/pointsto/heap/ImageHeapScanner.java
CONFLICT (content): Merge conflict in …
```

[Backport] [GR-59858] Mark type of hidden field reachable.

---

substratevm/src/com.oracle.svm.core.genscavenge/src/com/oracle/svm/core/genscavenge/BasicCollectionPolicies.java
substratevm/src/com.oracle.svm.core.genscavenge/src/com/oracle/svm/core/genscavenge/HeapChunkProvider.java
substratevm/src/com.oracle.svm.core.genscavenge/src/com/oracle/svm/core/genscavenge/HeapParameters.java
substratevm/src/com.oracle.svm.core.windows/src/com/oracle/svm/core/windows/WindowsPhysicalMemorySupportImpl.java
substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/IsolateArgumentParser.java
substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/SubstrateGCOptions.java
substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/code/AbstractRuntimeCodeInstaller.java
substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/heap/HeapSizeVerifier.java
substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jfr/JfrTypeRepository.java
substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/os/AbstractImageHeapProvider.java
substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/os/ChunkBasedCommittedMemoryProvider.java
substratevm/src/com.oracle.svm.graal/src/com/oracle/svm/graal/isolated/IsolatedRuntimeCodeInstaller.java

- https://github.com/oracle/graal/pull/10072
- commit_1: "Better messages for OutOfMemoryErrors. Other small fixes and cleanups."
- substratevm/src/com.oracle.svm.core.genscavenge/src/com/oracle/svm/core/genscavenge/BasicCollectionPolicies.java
- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/IsolateArgumentParser.java
- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/graal/snippets/CEntryPointSnippets.java
- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/os/AbstractImageHeapProvider.java
- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/os/ChunkBasedCommittedMemoryProvider.java
<details>
substratevm/src/com.oracle.svm.core.genscavenge/src/com/oracle/svm/core/genscavenge/BasicCollectionPolicies.java
- …

[Backport][GR-59582] Better messages for OutOfMemoryErrors and small cleanups/bugfixes.

---

substratevm/src/com.oracle.svm.core.genscavenge/src/com/oracle/svm/core/genscavenge/LibGraalCollectionPolicy.java

- https://github.com/oracle/graal/pull/11392
Closes: https://github.com/graalvm/graalvm-community-jdk21u/issues/180

[Backport] [Oracle GraalVM] [GR-65853] Backport to 23.1: Return correct name for libgraal-specific collection policy.

---

substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jvmstat/PerfManager.java

- https://github.com/oracle/graal/pull/11345
**Conflicts:** There were no conflicts. but I it needed to be adapted to avoid using `RecurringCallbackSupport` which is not present since
https://github.com/oracle/graal/commit/0a37b5f5622d238a5540d8ef80773630985d31a5
is not backported
**Closes:** https://github.com/graalvm/graalvm-community-jdk21u/issues/179

[Backport] [Oracle GraalVM] [GR-65664] Backport to 23.1: Rethrow OutOfMemoryErrors that happen during performance data initialization.

---

substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/image/sources/SourceManager.java

- https://github.com/oracle/graal/pull/11794
```diff
diff --cc substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/image/sources/SourceManager.java
index 6e5b030e025,f3d3e7c7a45..00000000000
--- a/substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/image/sources/SourceManager.java
+++ b/substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/image/sources/SourceManager.java
@@@ -160,7 -159,7 +160,11 @@@ public class SourceManager 
* A map from a Java type to an associated source paths which is known to have an up to date
* entry in the relevant source file cache. This is used to memoize previous lookups.
*/
++<<<<<<< HEAD
+    private static HashMap<ResolvedJavaType, Path> verifiedPaths = new HashMap<>();
++=======
+ …
```

[Backport] [Oracle GraalVM] [GR-68114] Backport to 23.1: Fix memory leak in SourceManager.verifiedPaths.

---

substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/NativeImageGeneratorRunner.java

- https://github.com/oracle/graal/pull/10260
Closes: https://github.com/graalvm/graalvm-community-jdk21u/issues/195

[Backport] [Oracle GraalVM] [GR-67898] Backport to 23.1: Avoid recursive printing of exception causes.

---

compiler/src/jdk.internal.vm.compiler.test/src/org/graalvm/compiler/replacements/test/PEGraphDecoderTest.java
compiler/src/jdk.internal.vm.compiler/src/org/graalvm/compiler/replacements/CachingPEGraphDecoder.java
compiler/src/jdk.internal.vm.compiler/src/org/graalvm/compiler/truffle/compiler/PartialEvaluator.java
compiler/src/jdk.internal.vm.compiler/src/org/graalvm/compiler/truffle/compiler/TruffleCachingConstantFieldProvider.java
compiler/src/jdk.internal.vm.compiler/src/org/graalvm/compiler/truffle/compiler/TruffleConstantFieldProvider.java

- https://github.com/oracle/graal/pull/11488
**Conflicts:**
- Merge issue: CachingPEGraphDecoder has a different parameter list on mainline vs. graalvm-community-jdk21u
- Resolution: adopt the mainline change by adding graphCacheProviders and decodingProviders; do not refactor or re-align surrounding code
```
<<<<<<< HEAD:compiler/src/jdk.internal.vm.compiler/src/org/graalvm/compiler/replacements/CachingPEGraphDecoder.java
public CachingPEGraphDecoder(Architecture architecture, StructuredGraph graph, Providers providers, GraphBuilderConfiguration graphBuilderConfig, OptimisticOptimizations optimisticOpts,
LoopExplosionPlugin loopExplosionPlugin, InvocationPlugins invocationPlugins, InlineInvokePlugin[] inlineInvokePlugins,
=======
public …
```

[Backport] [Oracle GraalVM] [GR-66289] Backport to 23.1: TruffleLogger.getLevelNum() causes deopt loops.

---

wasm/src/org.graalvm.wasm.benchmark/src/org/graalvm/wasm/benchmark/WasmBenchmarkSuiteBase.java
wasm/src/org.graalvm.wasm/src/org/graalvm/wasm/BinaryParser.java
wasm/src/org.graalvm.wasm/src/org/graalvm/wasm/SymbolTable.java
wasm/src/org.graalvm.wasm/src/org/graalvm/wasm/WasmCodeEntry.java
wasm/src/org.graalvm.wasm/src/org/graalvm/wasm/WasmInstantiator.java
wasm/src/org.graalvm.wasm/src/org/graalvm/wasm/memory/ByteArrayWasmMemory.java
wasm/src/org.graalvm.wasm/src/org/graalvm/wasm/memory/NativeWasmMemory.java
wasm/src/org.graalvm.wasm/src/org/graalvm/wasm/memory/UnsafeWasmMemory.java
wasm/src/org.graalvm.wasm/src/org/graalvm/wasm/memory/WasmMemory.java
wasm/src/org.graalvm.wasm/src/org/graalvm/wasm/nodes/WasmFunctionNode.java
wasm/src/org.graalvm.wasm/src/org/graalvm/wasm/parser/bytecode/BytecodeParser.java
wasm/src/org.graalvm.wasm/src/org/graalvm/wasm/parser/ir/CodeEntry.java
wasm/src/org.graalvm.wasm/src/org/graalvm/wasm/parser/validation/ParserState.java

- https://github.com/oracle/graal/pull/9457
-- **Excluding** https://github.com/oracle/graal/commit/a6fa57bc4d9fc68631d3dcfff6330b43c03ce9e3
**Issues:**
The Oracle GraalVM for JDK 21.0.6 backports log entry `"Remove constant memory buffer assumption"` only corresponds to the first commit `"Remove constant memory buffer assumption and simplify ByteArrayWasmMemory."` Backporting the other changes in [GR-56094 PR#9457](https://github.com/oracle/graal/pull/9457) is questionable:
- Remove constant memory buffer assumption and simplify ByteArrayWasmMemory.
- Check that memory 0 size >= initial size at the start of a wasm function.
This allows hoisting bounds checks for memory accesses that are guaranteed to stay within the initial …

[Backport][GR-56094] Remove constant memory buffer assumption and simplify ByteArrayWasmMemory.
